trustPolicy: off
trustLockfile: true
trustPolicyExclude:
  - 'chokidar@4.0.3'
  - '@types/node@25.9.2'
allowBuilds:
  better-sqlite3: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  usearch: true
