export {
  addMessage,
  clearChatMessages,
  classifyDeviceType,
  closeDb,
  createChat,
  deleteChat,
  deleteReaction,
  dismissFeatureTours,
  ensureModel,
  getChat,
  getChatEventsSince,
  getChatMessageCount,
  getChats,
  getDismissedFeatureTours,
  getExperience,
  getMessages,
  getMessagesByUserId,
  getOffTopicCount,
  getOrCreateUserAgent,
  getPosts,
  getReaction,
  getToolCallsByMessageId,
  getToolCallsForMessages,
  getUserChatCount,
  incrementOffTopicCount,
  insertChatEvent,
  insertContactIntent,
  insertLead,
  isChatLocked,
  lockChat,
  renameChat,
  searchChunks,
  setReaction,
  softDeleteMessage,
  updateUserContact,
} from './db/sqlite-legacy';

export type {
  StoredChunk,
  SearchResult,
  ToolCallRecord,
  StoredMessage,
  Chat,
  AddMessageParams,
} from './db/sqlite-legacy';

// Re-export SurrealDB service singleton for new consumers
export { db } from './db/index';
